#!/usr/bin/env bash
# A bash script that installs and fixes the 
#Nginx configuration file to listen on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
